### ISSUE TITLE
occasional SQLException causing app to crash

### ISSUE THREAD

**Issue by 1kylewilson** [1kylewilson/EverywhereClient#11]
`whereclient E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                                        Process: uk.co.everywheremusic.everywhereclient, PID: 14299
                                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                                         Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
                                                                                            at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                                                            at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
                                                                                            at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                                                            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                                            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
                                                                                            at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                                            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
                                                                                            at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
                                                                                            at uk.co.everywheremusic.everywhereclient.viewcontroller.listfragment.ListFragment$PopulateExtraInfoTask.doInBackground(ListFragment.java:392)
                                                                                            at uk.co.everywheremusic.everywhereclient.viewcontroller.listfragment.ListFragment$PopulateExtraInfoTask.doInBackground(ListFragment.java:341)
                                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                            at java.lang.Thread.run(Thread.java:818) 
02-07 11:59:53.136 14299-14332/uk.co.everywheremusic.everywhereclient E/Surface: queueBuffer: error queuing buffer to Surfac`

**Comment by 1kylewilson** [comment]
check for cursors being left open

**Comment by 1kylewilson** [comment]
Found 1 cursor not being close properly. Monitor for this, close if app doesn't crash because of this for a while.

**Comment by 1kylewilson** [comment]
no longer seems an issue, closing
